apiVersion: v1
kind: Pod
metadata:
  name: messaging
  labels:
    name: messaging
    tier: msg
spec:
  containers:
  - name: messaging
    image: redis:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379
