apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-app
  labels:
    name: multi-pod-app
spec:
  containers:
  - name: alpha
    image: nginx
    env:
    - name: Container 1  
      value: "alpha"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  - name: beta
    image: busybox
    env:
    - name: Container 2  
      value: "beta"
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 4800; done;" ]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8081

