apiVersion: v1
kind: Pod
metadata:
  name: nginx-critical
  labels:
    name: nginx-critical
spec:
  containers:
  - name: nginx-critical
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  nodeName: node01

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pod-restart
  namespace: default 
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-restart
  namespace: default
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["pod"]
    resourceNames: ["nginx-critical"]
    verbs: ["get", "patch", "list", "watch"] 
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-restart
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-restart
subjects:
  - kind: ServiceAccount
    name: pod-restart
    namespace: default
