apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-andrew
  labels:
    name: redis-storage-andrew
spec:
  containers:
  - name: redis-storage-andrew
    volumeMounts:
      - mountPath: /data/redis
        name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
    image: redis:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379
