apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-analytics
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /pv/data-analytics
    server: 172.17.0.2

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: use-pv
  name: use-pvspec-yourname
  containers:
  - image: nginx
    name: use-pv
    resources: {}
    volumeMounts:
    - name: vol
      mountPath: /data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}